### ISSUE TITLE
Audio Crackling issue fixed

### ISSUE THREAD

**Issue by johnnyq** [Turro75/MyMinUI#11]
I was comparing your MyMinUI to shauninman/MinUI and noticed your MyMinUI fixed a major audio crackling issues on Super Nintendo on the Miyoo Mini Plus. This is testing the latest version in both repos as of 2024-07-13 Would you be so kind to point out your commit that fixed this issue?
Thank you for your hard work that you put into MyMinUI.

**Comment by johnnyq** [comment]
Seems to have fixed the audio crackling between these versions: https://github.com/Turro75/MyMinUI/compare/MyMinUI-20240602b...MyMinUI-20240627b not sure what commit did it though

**Comment by johnnyq** [comment]
Further investigating I'm guessing this is what may have fixed the audio crackle
https://github.com/Turro75/MyMinUI/commit/0986db0653e4161b920594acd7a38a7aa08b51e0

But it doesn't matter if I turn it on or off in the emulator the audio doesn't crackle which is a good thing, just super curious what may have fixed it, as it drove me crazy for a long time with MinUI

**Comment by Turro75** [comment]
I don't remember any audio issue on snes, I think the most involved one would be the commit efb7699 which removed a libmsettings dependency from some specific audio miyoo libs which was the cause for audio muted on nds/pico8. Other than that it seems nothing has been actually done or maybe a mix of the mentioned commits.

**Comment by johnnyq** [comment]
@Turro75 Thats fantastic im deff not complaining just hope to pass the fix on to @shauninman from MinUI
I have a sensitive ear I guess good work btw it was the only thing keeping me from using MinUI.

**Comment by johnnyq** [comment]
Technically this can be closed as its not an issue but just pointing to an issue that was fixed that shpould be replicated to MinUI repo.
