### ISSUE TITLE
Rewind Support

### ISSUE THREAD

**Issue by johnnyq** [Turro75/MyMinUI#15]
Not sure if this is even possible with MinUI but rewind support would be awesome while still using minarch instead of retroarch for its simplistic menu?

**Comment by Turro75** [comment]
well, not exactly on top of the todo list....let me finish a couple of milestones (i.e. powersave mode even with retroarch) then I'll have a look if can be done without becoming mad.

**Comment by johnnyq** [comment]
I really appreciate you looking into if its even possible. These older games are tough and would be nice to rewind a little bit if I F up somewhere, but please we don't want you goin mad over it so take your time, Ive seen one too many developers go mad.

**Comment by Turro75** [comment]
I investigated a bit on rewind, it looks something that put a lot of load over the cpu. I pass.
