### ISSUE TITLE
Source for FBENEO map.txt file?

### ISSUE THREAD

**Issue by lemonzest79** [Turro75/MyMinUI#16]
Hi

I was wondering the source for the map.txt file for final burn neo, from the look of it it seems sourced from mame? would it be possible to source from fbaneo itself? cos some roms are missing from the list that fbaneo supports, mostly hacks but supported anyways

Thank you

**Comment by Turro75** [comment]
it is based on the arcade-rom-name.txt available in onionos, simply the result fo a couple of find/replace actions with vscode
