### ISSUE TITLE
Port to the many H700 Anbernic Form Factor Devices

### ISSUE THREAD

**Issue by johnnyq** [Turro75/MyMinUI#22]
Any chance of porting to the many Anbernic H700 Devices (RG35XX Plus, RG35XX 2004, RD35XX SP, RG28XX, RG 40XX V, RG 40XX H, RG Cube XX)

maybe, possibly could use rocknix or MuOS as a base if that makes it any easier to port and for cross compatibility

I'm really liking the MiniArch Doom and Arcade support in which were missing with the the standard MinUI.

**Comment by Turro75** [comment]
Not soon, for 2 reasons:
1) I don't have any of them, so it's nearly impossible supporting these devices without extensive testing.
2) MinUI for these devices uses libSDL2, MyMinUI does not work so well with libSDL2, once fixed the A30 which also runs libSDL2  it could be ported to h700 platform, but, again nothing from my side unless I have a physical device in my hands.

**Comment by johnnyq** [comment]
Hey @Turro75 i have a few h700 any in particular you looking for I could ship you a few of em if your in the US if your interested

**Comment by Turro75** [comment]
Thanks for the proposal, I'm based in Europe/Italy so maybe another time. Anyway it could be that the next blackfriday will bring a monkey on my shoulder shouting "take it! take it!".
Jokes apart the h700 is powerful and has a lot of features that Minui doesn't support (gpu, hdmi, external controller, wifi, multiplayer, etc...) in my opinion (my)minui in these level of devices is not the best choice. You are probably in love (like me) of the daily minui's user experience which is amazing compared to the other retroarch based systems but if I take an h700 device I expect to be able to use all the available features.

**Comment by johnnyq** [comment]
Ah gotchya, but yes totally love the MinUI's interface in fact I think its a master piece of shear beauty and simplicity.
Totally understand where your coming from. I think the H700 is very important as it takes on many form factors and would cross compile across the board with the display being the only difference on each.

**Comment by Turro75** [comment]
I close this request, the blackfriday didn't make me enough mad to get another handheld.
Maybe a 4" clamshell would make me change my mind.
