### ISSUE TITLE
Drastic makes others cores to crash on miyoo mini

### ISSUE THREAD

**Issue by pakrett** [Turro75/MyMinUI#25]
On my miyoo mini when play a DS game then quit drastic I can not launch a game from another platform, it results in a black screen and I have to remove the battery to shutdown the console.

(I use drastic 1.8 on MyMinUI 20241110b and I launch it with your method by copying the "drastic" folder into NDS.pak)

**Comment by pakrett** [comment]
I have fixed the issue by replacing these lines into /Emus/miyoomini/NDS.pak/launch.sh

```
if $IS_PLUS; then
    /customer/app/audioserver -60 &
else
    ${SDCARD_PATH}/.system/miyoomini/bin/audioserver.mod -60 &
fi
```
by this

```
if $IS_PLUS; then
	/customer/app/audioserver -60 & # &> $SDCARD_PATH/audioserver.txt &
	export LD_PRELOAD=/customer/lib/libpadsp.so
else
	if [ -f /customer/lib/libpadsp.so ]; then
	    LD_PRELOAD=as_preload.so audioserver.mod &
	    export LD_PRELOAD=libpadsp.so
	fi
fi
```

**Comment by Turro75** [comment]
Thanks for the hint, I don't own a miyoo mini, just the plus. In fact the libpadsp is used by the mini. I'll fix in the next release.

Menu+power should be act as hardware reset (at least on plus)

**Comment by Turro75** [comment]
fixed here: https://github.com/Turro75/MyMinUI/commit/ef671a619b15b3dcce1d14aa2e6f10376505caf9

Thanks!
