### ISSUE TITLE
Screen flickering / flashes on DS games with drastic on miyoo mini

### ISSUE THREAD

**Issue by pakrett** [Turro75/MyMinUI#26]
Screen flickering / flashes on DS games with drastic.
Most of the time it only concerns the secondary screen, and sometimes the primary one have some artifacts lines on top.
It doesn't matter if it's the top or bottom screen but the one that is selected as main screen.

(I use drastic 1.8 on MyMinUI 20241110b and I launch it with your method by copying the "drastic" folder into NDS.pak)

**Comment by pakrett** [comment]
The issue appeared in version 20240627b, in 20240602b everything worked well.

I've used the lastest "launch.sh" script present in version 20241110b to launch drastic on both these MyMinUI version and on version 20240602b sound and graphics works perfectly with no issues.

**Comment by pakrett** [comment]
The culprit is "lumon.elf" in \.system\miyoomini\bin
I've replaced it by the one from version 20240602b

You also need to edit "launch.sh" in \.system\miyoomini\paks\MinUI.pak
At line 91 change "lumon.elf #&" to "lumon.elf &"

I've done the modifications to MyMinUI 20241110b and now everythings works perfectly.

**Comment by Turro75** [comment]
Fixed here https://github.com/Turro75/MyMinUI/commit/ef671a619b15b3dcce1d14aa2e6f10376505caf9

thanks!
