### ISSUE TITLE
Left and right dpad page seek

### ISSUE THREAD

**Issue by sgorveatt** [Turro75/MyMinUI#8]
On Minui you are able to navigate page up and down by hitting right or left on the dpad, respectively. It's a very fluid and intuitive way to navigate large lists.

I'm unable to do this on Myminui. Is this intentional or a bug? I'm aware that shoulder buttons allow for faster navigation, but it's not ideal.

Forgot to mention, I'm using a Miyoo Mini Plus.

Also great work on your OS.

**Comment by laesetuc** [comment]
I would love to see this (re-)implemented as well!
As far as I know I think this behaviour was changed in FinUI and MyMinUI has inherited it.

**Comment by Turro75** [comment]
I changed left and right behavior as I actually prefer selecting states with left/right and triggers for quick letters/page s scrolling.
Do You mean auto re-establish left/right for pages while in standard/simple mode and navigating across states while in fancy mode or simply a toggle under tools that switches the minui/myminui  behavior independently of the chosen mode?

**Comment by laesetuc** [comment]
I think we are talking about using left/right to navigate game lists here. 
In MinUI this allows you use the dpad to scroll single items using up/down or pages using left/right. 

In settings menus this wouldn’t make sense.

**Comment by Turro75** [comment]
New release available, I've added a toggle tool, with this toggle off  the dpad left and right back to standard minui behavior, activating the toggle move to myminui dpad button behavior  (state select) while seek page function is moved to L2-R2.

**Comment by Turro75** [comment]
Added feature to handle the request
