### ISSUE TITLE
Feature requests....

### ISSUE THREAD

**Issue by 05warmupsdelayer** [Turro75/MyMinUI#9]
Ya know, this is almost a **FullUI** now :) 

Some things that I would change if I knew how...

1) Move the Settings > Toggles into options the Main Menu Screen menu button (where the mode toggle Is set)
2) Add a Toggle option there for Hidden Folder. (I do not need it) 
3) Add a Toggle option there for default minarch / retroarch preference. 

That it. 

Thank you for your service.

**Comment by Turro75** [comment]
1) I have to think about it twice, it's not as easy as it's look like and the reward is tiny.
2) probably You are not an european coin up arcade  player :-) I'll check what to do in that sense.
3) unless I'll be sure all cores can run on both frontend without issues I won't do that, I prefer leaving the default choice for each core by editing the launch.sh file.

**Comment by 05warmupsdelayer** [comment]
Okay thanks. 👍
